---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# go-task runner file - rest of config in .taskfiles/**.*.yaml
version: "3"

includes:
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops

tasks:
  default:
    silent: true
    cmds:
      - task -l